### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/rfcs#1]
The debugger is using it now

**Comment by jryans** [comment]
I think this is safe to use in Firefox now. JS team had originally asked for a cycle delay to work out issues, but that was in 52 and we're in 54 now.

The only disadvantage I know of vs. the Task library is that you don't get unhandled promise error reporting, but that's not really critical, just a nice to have.

**Comment by juliandescottes** [comment]
This is now commonly used in DevTools. Closing
