### ISSUE TITLE
build eslint file based on pre-configured rules

### ISSUE THREAD

**Issue by gasolin** [devtools-html/rfcs#13]
Our current eslint is hand crafted and still need reviewer to address several code style issues

We could improve the situation by build on top of well maintained style, ex: airbnb, and add our flavor upon it

Ref: 
* current devtools coding standards https://wiki.mozilla.org/DevTools/CodingStandards
* AirBnb preconfigured eslint rules https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by juliandescottes** [comment]
Hi @gasolin 

Sorry for reviving a very old issue! Before diving into your proposal here, is it still a valid question, did you try to address/discuss this somewhere else?

Let's update this issue and make some progress :)

**Comment by juliandescottes** [comment]
Closing, please reopen if needed.
