### ISSUE TITLE
move rfcs into devtools-core

### ISSUE THREAD

**Issue by gasolin** [devtools-html/rfcs#15]
Since https://github.com/devtools-html/devtools-core is already a all-in-one repo for devtools, there will be more drop by eyes there and we have better change to get more feedback once anyone propose a RFC.

Do we need separate `rfcs` repo to host only RFC?

**Comment by clarkbw** [comment]
Good question.  I want this repo to be owned / maintained by a set of people who might not be the set of people who maintain the devtools-core repo.  For example I (a PM) shouldn't be a maintainer of devtools-core but should be one for this repo.

**Comment by jryans** [comment]
We might also want the RFCs to cover multiple DevTools repos, even with a single "main" repo. Foe example, even if we consolidate most code into `devtools-core`, we might have other ancillary tools / projects that are still covered by RFCs, so this suggests a separate RFC repo to me.

**Comment by gasolin** [comment]
Make sense, thanks
