### ISSUE TITLE
Remove the options panel shortcut Ctrl+Shift+O 

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/rfcs#23]
The CmdOrCtrl+Shift+O currently toggles DevTools options. The Debugger also uses CmdOrCtrl+Shift+O to toggle function search. This shortcut has an inconsistent behavior depending whether the user is on the Debugger or on another panel.

We are proposing to remove the "options toggle" command and keep only the debugger function search command. Main reasons:
- the F1 shortcut which also toggles the options panel
- CmdOrCtrl+Shift+O for function search is consistent with the Chrome Debugger

The following documentation pages are currently referencing the shortcut:
- https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox
- https://developer.mozilla.org/en-US/docs/Tools/Settings

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1409456

**Comment by jryans** [comment]
Seems fine to remove options toggle to me. (To be honest, I didn't know it had any shortcuts at all!)

**Comment by digitarald** [comment]
LGTM (also didn’t know)

**Comment by jasonLaster** [comment]
yep. I strongly support this :)

**Comment by captainbrosset** [comment]
I knew about this shortcut. I did not know about F1 though 😄 

Removing keyboard shortcuts always feels uncomfortable. Especially without knowing the usage from data.

I think it might be fine here to remove the shortcut without knowing the usage, for a few reasons:

- the options panel is not used a lot at all (just checked on telemetry, while the inspector is over 100.000, options is at 3000).
- F1 would still work.
- https://developer.mozilla.org/en-US/docs/Tools/Settings mentions F1, and mentions it first, before the CmdOrCtrl+Shift+O shortcut.
- And CmdOrCtrl+Shift+O does not appear in a tooltip when hovering the options tab, unlike when hovering, say, the inspector. So there's never been an in-tool hint that this shortcut even existed.

**Comment by juliandescottes** [comment]
Thank you all for the feedback, and thanks for the detailed info from @captainbrosset 
We will look at this item during next week's RFCs review.

**Comment by juliandescottes** [comment]
This RFC was accepted: the CmdOrCtrl+Shift+O shortcut will no longer toggle the options menu. Follow-up work will be done in https://bugzilla.mozilla.org/show_bug.cgi?id=1409456

**Comment by juliandescottes** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409456 landed
