### ISSUE TITLE
Preferred method for adding static properties to components

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/rfcs#24]
I have created an AST transformer to change our ES5 classes to ES6.

At the moment it adds static properties like this:

```
class Font extends Component {
  ...
}

Font.displayName = "Font";
etc.
```

But we could keep all the static properties inside the class body like this:

```
class Font extends Component {
  static get displayName() {
    return "BoxModelMain"
  }
  ...
}
```

Which do you prefer? It makes sense for us to have a consensus before we change a gazillion files.

**Comment by gabrielluong** [comment]
I prefer keeping all these static properties inside the class body.

**Comment by jryans** [comment]
I would like to keep them in the class body, mostly so that the ordering of properties doesn't need to change.

**Comment by janodvarko** [comment]
Yes, I also vote for keeping it in the class body (list of props can stay nicely at the beginning).

Honza

**Comment by rickychien** [comment]
I'd like to say in general cases, it's not that useful to create a customized `displayName` for react component. According to react document [1], you don’t need to set it explicitly.

For other cases, `static defaultProps`, `static propTypes` and `state` are better.

I'd suggest something like that.

```js
class Font extends Component {
  static defaultProps = {

  }

  static propTypes = {

  }

  state = {

  }

  render() {
     ...
  }
}
```

[1] https://reactjs.org/docs/react-component.html#displayname

**Comment by MikeRatcliffe** [comment]
@rickychien Firefox does not support static properties. Using `static` in the way you suggest would throw a syntax error in Firefox 58.

We could use Babel to transpile the code but we do not want to create an extra build step if we don't need to do so.

Seems like most everybody prefers using static getters so I will get right onto it.

**Comment by juliandescottes** [comment]
+1 to keep them in the class body.

Should we try to annotate those getters in order to migrate them to static properties / fields whenever they becomes an ES valid syntax? (https://github.com/tc39/proposal-class-fields ?)

> Seems like most everybody prefers using static getters so I will get right onto it.

In theory we wait until the RFC has been reviewed before moving forward :) . Reviews every Thursday, will be mentioned in DevTools weekly meeting. Want to make sure most have had the opportunity to share their opinion.
Maybe that's too slow when a RFC seems to have reached consensus already? Since this one was opened during the weekend maybe we can wait a bite more, but I can see how the process could just be slowing us down in some cases.

**Comment by MikeRatcliffe** [comment]
@juliandescottes We don't need to annotate the fields as it would be a simple mater of creating a new AST transform in order to change them.

Adding this functionality now makes sense, at least as an option e.g. `--static-getters`,  because no other tools appear to offer this functionality.

**Comment by juliandescottes** [comment]
Ok, thought we might have trouble differentiating between the ones generated here and static getters we could later add for other reasons. 

> Adding this functionality now makes sense, at least as an option e.g. --static-getters, because no other tools appear to offer this functionality.

Sure go ahead 👍  Let's just keep the discussion open before landing the refactor.

**Comment by MikeRatcliffe** [comment]
Done: https://github.com/MikeRatcliffe/moz-codemod/commit/3f7614334dfca494789a5dda99d9e637a3a64b63

**Comment by juliandescottes** [comment]
This RFC was accepted: @MikeRatcliffe you can go ahead and update your refactor patches with this change.
