### ISSUE TITLE
When moving to ES6 classes should we drop displayName?

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/rfcs#25]
@rickychien has requested that we remove displayName because according to a React document [1], you don’t need to set it explicitly.

Of course, it was never needed for Components created using createClass() either but since we are changing lots of components at the same time let's get this right.

Should displayName live or die? You decide!

You can use the thumbs up or thumbs down icons to vote quickly.

[1] https://reactjs.org/docs/react-component.html#displayname

**Comment by MikeRatcliffe** [comment]
I like displayName, let's keep it!

**Comment by MikeRatcliffe** [comment]
I don't like displayName, let's drop it!

**Comment by gasolin** [comment]
As react document described https://reactjs.org/docs/react-component.html#displayname

`displayname` is optional and just usefal when you want to display a different name for debugging purposes or when you create a higher-order component. These 2 are not the case in our code base.

**Comment by jryans** [comment]
In the past, I've used the [React Perf tools][1] to track slow components, etc. Do these still print a reasonable name for the component without `displayName`? (I realize they aren't supported in React 16, but I still have the same question about the [new approach][2] using performance / tracing tools.)

Hopefully these tools all show reasonable names without `displayName`, but someone should double check to make sure. If so, I think it's fine to remove.

[1]: https://reactjs.org/docs/perf.html
[2]: https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab

**Comment by MikeRatcliffe** [comment]
> In the past, I've used the React Perf tools to track slow components, etc. Do these still print a reasonable name for the component without displayName?

Yes they do... they just use the class name, which is normally the same as the displayName.

Sadly, the perf tools may not appear for quite some time because of fundamental changes to some of React's internals.

I am planning on converting my whydidyouupdate and objectdiff mixins to high order components so that they will work with the ES6 classes... these will need to get the name too but it won't be a problem.

**Comment by jryans** [comment]
(I assume the thumbs down reactions on dropping the name are actually votes to support that plan.)

**Comment by juliandescottes** [comment]
The second option from this RFC was accepted: drop displayName.
@MikeRatcliffe you can go ahead and update your patches according to this.
