### ISSUE TITLE
Remove 'devtools reload' addon?

### ISSUE THREAD

**Issue by bgrins** [devtools-html/rfcs#28]
We have an addon in https://dxr.mozilla.org/mozilla-central/source/devtools that allows a developer to easily reload the toolbox. See https://hacks.mozilla.org/2016/02/introducing-devtools-reload/ for more information.

I have a needinfo out for me in https://bugzilla.mozilla.org/show_bug.cgi?id=1241131#c6 which refers to the new [keyboard shortcuts added local builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1385452) that allow a developer to quickly restart firefox. The new shortcut doesn't quite match the feature set exactly for the devtools reload addon:

1) It still requires some work for `./mach watch` to work well (which is needed to get changes into the objdir on windows) - https://bugzilla.mozilla.org/show_bug.cgi?id=1386040 and potentially some python dependency issues windows).
2) It still requires a local build (although now with artifact builds it's a bit less of a burden)

It seems that the primary win with the addon is (2) in that you could just download Nightly and check out m-c and still be able to make changes. However, when trying to load the devtools reload addon (in a local build) to test it out I got an error:

> There was an error during installation: Add-on devtools@mozilla.org is not compatible with application version. add-on minVersion: 57.0a1. add-on maxVersion: *.

Which makes me think that perhaps this isn't being used. Is anyone using this addon for working on devtools? If not then I'd propose that we remove it to simplify the options we present for contribution and to clear out the top level `devtools/` directory a bit.

**Comment by gregtatum** [comment]
I do not use it, and I didn't when I was working in m-c every day. I agree to remove and lower our maintenance burden.

**Comment by nchevobbe** [comment]
Same here, I am now using the Cmd + Alt + r shortcut which I find fast enough to be satisfying

**Comment by juliandescottes** [comment]
For the record, for go-faster we were actually getting rid of the reload capabilities of the addon and simply converting this to the devtools system-addon.

Some of the patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1369801 are specifically about simplifying the bootstrap.js code. For instance you can see the bootstrap.js as it looked like when we briefly landed this: https://hg.mozilla.org/mozilla-central/file/ad2610a5e6ba/devtools/bootstrap.js

It's not clear what will happen to the current gofaster/system-addon effort, but one option would be to land all the go faster patches aiming to simplify the addon code?

**Comment by gabrielluong** [comment]
Agreed with the removal. It is not something I use or recommend to any new contributors/student. I also believe there are issues with the devtools reload addon workflow since you had to have the source code and load the addon every time. I believe one of the core problem this was trying to solve was building the source code.  Now that we have artifact builds and the entire build process is rather quick and ./mach watch in the future, I see little need for this. Also, we should keep in mind some number of tools take advantage of launchpad and does not require this functionality or is incompatible with this addon in some sense.

**Comment by ochameau** [comment]
> For the record, for go-faster we were actually getting rid of the reload capabilities of the addon and simply converting this to the devtools system-addon.
>
> Some of the patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1369801 are specifically about simplifying the bootstrap.js code. For instance you can see the bootstrap.js as it looked like when we briefly landed this: https://hg.mozilla.org/mozilla-central/file/ad2610a5e6ba/devtools/bootstrap.js
>
> It's not clear what will happen to the current gofaster/system-addon effort, but one option would be to land all the go faster patches aiming to simplify the addon code?

+1, I thought these patches were already landed.
bootstrap.js can be stripped down from all hot reload features, but should be kept around as part of gofaster initiative. Unless we want to get rid of gofaster, in such case, the cleanup would be bigger.

**Comment by captainbrosset** [comment]
+1 on removing this reload feature.

**Comment by juliandescottes** [comment]
RFC reviewed and accepted. We will repurpose https://bugzilla.mozilla.org/show_bug.cgi?id=1241131 to remove the reload features of the addon.
