### ISSUE TITLE
Create a new DevTools product on bugzilla, move all our bugzilla components under it and all our bugilla bugs

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/rfcs#29]
Right now, on bugzilla, all of the DevTools components are inside the Firefox product.

The proposal is to create a top-level DevTools product, for better discoverability.
Our components would therefore move under this new product, and all our bugs too.

The bug to follow about this is: https://bugzilla.mozilla.org/show_bug.cgi?id=1420561

Current discussions about this:

* Should we expect a massive bugmail storm when this happens? If so, will there be a keyword we can filter on?
> Emma: No, we do this in a way that doesn't trigger bugmail.

* Would we lose some kind of history in the move?
> Emma: No.

* Will it touch old bugs we would like to keep "untouched"? Sometimes, it's useful to search for bugs by when they were last touched. Is this going to reset this date for all bugs?
> Emma: I don't believe it will, but asking :dylan to confirm.
(no response from Dylan yet).

This move would give us the ability to make our component names shorter too (they won't need to have the "Developer Tools:" prefix). We'll need to create a new one for the general "Developer Tools" component. Maybe "General".

**Comment by julienw** [comment]
Another question: will URL like https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Debugger be redirected to using the right product and component too? I believe these URLs are used in some places like mail archives, etc, and it would be a shame that the [old URLs don't work anymore](https://www.w3.org/Provider/Style/URI.html).

**Comment by juliandescottes** [comment]
> The proposal is to create a top-level DevTools product, for better discoverability.

To make it obvious, I really prefer having "DevTools" rather than "Developer Tools". Shorter & more url friendly.

> Will it touch old bugs we would like to keep "untouched"? Sometimes, it's useful to search for bugs by when they were last touched. Is this going to reset this date for all bugs?

This is the main thing I am concerned about. If it does "touch" the bugs, then I'd like us to perform an old-bugs-triage before the move.

> We'll need to create a new one for the general "Developer Tools" component. Maybe "General".

"General" sounds good.

**Comment by Garbee** [comment]
What is the benefit to moving issue discussion into bugzilla? I've noticed that the less things are on an easy open platform like GitHub the fewer external contributors that will end up helping out.

**Comment by juliandescottes** [comment]
@Garbee I believe we're only talking about renaming existing Bugzilla components. We are not moving GitHub issues to Bugzilla.

**Comment by Garbee** [comment]
Well, "all" yes set off an alarm. But also this being on GitHub and discussing moving things into a bugzilla project, I assumed the link was in that direction as well.

Ignore me, all clear now. Thank you @juliandescottes.

**Comment by sole** [comment]
I'm in favour of this.

1) It makes it more obvious that DevTools is a product by itself (I wonder if this will make it easier for Emma to triage as we won't be in their way?)
2) It makes it easier for bugs filed by new contributors to not to be lost until someone triages and assigns the right component.

The only downside I can think of is that maybe apps or other tools we've built around the Bugzilla [Rest] API might stop working until their parameters are updated (`Product` going from `Firefox` to `DevTools`, `Component` going from `Developer Tools: XYZ` to just `XYZ`)

**Comment by jryans** [comment]
> Another question: will URL like https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Debugger be redirected to using the right product and component too? I believe these URLs are used in some places like mail archives, etc, and it would be a shame that the old URLs don't work anymore.

My understanding is that Bugzilla doesn't do URL redirection from the old component names, so links like that to enter bugs as well as any custom queries that filter by component would all need to be updated manually.

**Comment by juliandescottes** [comment]
This RFC has been reviewed and accepted. 

2 non blocking issues:
- can previous links redirect to the new component (if not, that's too bad but we can live with it)
- will bugs be left untouched by the move (if not, need to triage first)

Let's make sure we have a communication plan + have updated all our docs when doing the move.

@pbro are you ok with taking this one?

**Comment by captainbrosset** [comment]
Sure. I'll get that going again in the new year.
Thanks for circling back on this.

**Comment by juliandescottes** [comment]
Great, closing!

**Comment by juliandescottes** [comment]
This is now implemented
