### ISSUE TITLE
Should RFCs be numbered?

### ISSUE THREAD

**Issue by sole** [devtools-html/rfcs#3]
The template is called `0000-template.md` but the current RFCs do not have a number in their file name. Should they?

I guess I'm used to internet RFCs with numbers, like the IETF's: https://www.rfc-editor.org/rfc-index.html

Ember's and Rust's also have numbers:
https://github.com/emberjs/rfcs/tree/master/text
https://github.com/rust-lang/rfcs/tree/master/text

I'd suggest we have numbers if only for consistency with other RFCs 😃

**Comment by jryans** [comment]
I like numbers too! :grin:

**Comment by clarkbw** [comment]
Ember is using the PR number to number the RFC.  So you start with `0000-template.md` and once you've made your PR you can update the file to equal the PR number.  So PR #6 would be `0006-template.md`.

**Comment by clarkbw** [comment]
> Ember is using the PR number to number the RFC

Also, the README should make this clear, since it is not.
