### ISSUE TITLE
Remove mozilla/devtools repo

### ISSUE THREAD

**Issue by jryans** [devtools-html/rfcs#32]
It appears there is an old DevTools planning repo living at [mozilla/devtools](https://github.com/mozilla/devtools) that predates nearly everyone on the team today (last modified in 2011).

Recently, an issue was opened (mozilla/devtools#2) there mentioning that the repo appears in search results, making it harder to find active repos.

I think it would be best to remove this old repo entirely to avoid confusion.

**Comment by clarkbw** [comment]
I would recommend updating the README to point to this org and then archiving the old repo so it can no longer be used.

To Archive, go to settings: https://github.com/mozilla/devtools/settings
Scroll down👇 
<img width="768" alt="screen shot 2018-01-04 at 11 44 29 am" src="https://user-images.githubusercontent.com/2134/34581257-ac7c9432-f144-11e7-83ba-276ee87038ca.png">

**Comment by jryans** [comment]
If there's anything worth keeping, then archive could make sense. As I see it though, the repo contains nothing of value anymore...

It contains:

* [Project dashboard](http://mozilla.github.io/devtools/status/index.html#summary) used around Firefox 8 timeframe
* A link to a roadmap on wiki.m.o, which has since been deleted

**Comment by clarkbw** [comment]
> As I see it though, the repo contains nothing of value anymore...

Sounds good.  Thanks for reviewing it, I completely forgot what was in there.

**Comment by juliandescottes** [comment]
The only concern would be about existing resources linking to this repository. If there were such resources, archiving and linking to a more relevant resource would make sense.

I could not find any link to this repository on Google though, so I'd say deleting is ok here.

**Comment by captainbrosset** [comment]
Yup, nothing of value over there, and it's very unlikely that other resources would link to this, and if there are, they are most probably outdated too. We should delete this repo.

**Comment by clarkbw** [comment]
Have a look at the traffic graphs https://github.com/mozilla/devtools/graphs/traffic to see if there are external links coming in.

**Comment by jryans** [comment]
Repo deletion complete. 🎉
