### ISSUE TITLE
Sentence spacing style in comments

### ISSUE THREAD

**Issue by jryans** [devtools-html/rfcs#37]
There appear to be 2 major approaches to sentence spacing style in code comments. Pulling random examples from the tree not written by me:

## Single space after period
```
    // Don't require a default case in switch statements. Avoid being forced to
    // add a bogus default when you know all possible cases are handled.
```
## Double space after period
```
 * Shut down the service, unregistering its event listeners and
 * flushing the cache.  After this call the service will no longer
 * function.
```

Recently, I have noticed reviewers pushing for single spacing, while my personal instinct is to use double spacing when writing in monospaced fonts (such as in a code editor). Mozilla coding style doesn't appear to mention this topic, and the tree contains numerous examples of both styles.

So, I'd like to make some determination about this topic to save future review time. Should we decide to:

* A. Only allow single space after period
* B. Only allow double space after period
* C. Either is acceptable

## Miscellaneous facts

* There's a [Wikipedia article](https://en.wikipedia.org/wiki/Sentence_spacing) about this subject (including a "Controversy" section). 😬 
* It [appears](https://en.wikipedia.org/wiki/History_of_sentence_spacing#French_and_English_spacing) that in the typewriter era, French typists used single spacing, while English typists used double spacing.

**Comment by nchevobbe** [comment]
I won't surprise anyone, I'm in favor of single space. I'd say that we are not in the typewriter era anymore, so we can let go the double space. English written books and newspaper use single spacing as well.

**Comment by juliandescottes** [comment]
Quickly looking through our code base, I find:
- `\. {1}[A-Z]` 13000 hits for dots followed by single spaces
- `\. {2}[A-Z]` 1300 hits for dots followed by double spaces

Given that we are already using single space way more than double space, I would go for either A or C. To reduce friction at review time, that would mean A enforced via linting I guess? C would be more or less the same as today, except we would have somewhere in the doc that we accept both (will be hard to make sure every reviewer always aware remembers that)

**Comment by julienw** [comment]
I'm more for C: I don't really mind, both work for me.

**Comment by bradwerth** [comment]
A all the way. One space after periods.

**Comment by gabrielluong** [comment]
I vote for A.

**Comment by jasonLaster** [comment]
A. and we fail eslint hard on 2 spaces. followed by a twitter-bot shaming of the commit...

**Comment by captainbrosset** [comment]
My vote goes to C: this doesn't impact me at all when reading the code, and doesn't impact the way it runs either.
And, to be honest, if a reviewer comments on this during a review, I'll just ignore it.

**Comment by juliandescottes** [comment]
Based on the current comments, most popular options are:
- A: Enforce single space
- C: Both are valid

After discussing this during the last RFC review, we feel that trying to enforce A via manual reviews will be frustrating for the reviewee. There is no eslint rule available to enforce this at the moment, so we would need to create one. 

In the meantime, we would follow option C: accept both, document it as such in the devtools documentation. Documentation would state that both styles are accepted and are not worth creating issues during a review.

If someone really feels strongly about this and wants to spend time creating a linter for that, we would agree to enable it and enforce A.

If you commented in favor of A, can you let us know if you are ok with this?
@gabrielluong  @jasonLaster  @bradwerth  (@nchevobbe  ?)

**Comment by juliandescottes** [comment]
During this RFC's review, we also discussed about reviews in general in devtools. There is a lack of guidelines and consistency when it comes to reviews, and that can be frustrating. Maybe be we can agree on rules to frame the reviews? Reviews are always a bit of a grey area between reviewer and reviewee, but we think the situation can be improved. 

@gregtatum brought up this point during the meeting and agreed to open a RFC to start discussing the issue.

**Comment by juliandescottes** [comment]
Thanks! I was pretty sure we had a document somewhere, but couldn't find it.

**Comment by jryans** [comment]
The same content also appears at:

http://docs.firefox-dev.tools/contributing/code-reviews.html
http://docs.firefox-dev.tools/contributing/javascript.html#comments

(I thought we had been removing content from wiki once it was migrated to the newer docs location in tree? We may need to do so here as well.)

**Comment by juliandescottes** [comment]
> If you commented in favor of A, can you let us know if you are ok with this?

If no one objects by next Monday, I'll consider that everyone is OK and we will move forward with option C. 

Regarding actual actions here:
- there will be a new RFC/documentation proposed by @gregtatum to make the review guidelines more practical
- remove the wiki pages mentioned above since the content is duplicated in the docs
- maybe still mention that we accept both in the coding style for devtools, just as we wait for the better documentation to be ready

**Comment by gregtatum** [comment]
I posted the higher level code review RFC: https://github.com/devtools-html/rfcs/issues/41

I think another action item here is to open up another RFC to update our list of recommended things to look for in code reviews, as when I read through it it seemed out of date. I'd prefer to defer this until after #41 is discussed.

http://docs.firefox-dev.tools/contributing/code-reviews.html

**Comment by juliandescottes** [comment]
Thanks @gregtatum ! Marking this RFC as accepted and proceeding to delete the wiki pages.
