### ISSUE TITLE
Drop the left paren space function() {}

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/rfcs#38]
It'd be great to revisit the decision to lint for a space before paren.

e.g.  `function () {}` , `function * () {}` 

There are a couple reasons why this is possible. 

1. @ochameau did a great job converting our Tasks to Promises [here]. It looks like we have two additional minor uses [here2].

2. the initial reason for the decision was a limitation of eslint [bug]. We wanted this syntax, but it could not supprt it. [pr]

```js
function name() {}
let f = function() {}
function* gen() {}
let g = function*() {}
let m = { * method() {} }
```

Since then, eslint has gotten better so we might be able to have the syntax we want. [pr]

Thanks @jryans for the helpful links/context.

[here]: https://github.com/mozilla/gecko-dev/commit/6ecbf50249d760c6ac47a2a73768da6249fecf3d
[here2]: https://searchfox.org/mozilla-central/search?q=function+*&path=devtools
[bug]: https://github.com/eslint/eslint/issues/6195
[pr]: https://github.com/eslint/eslint/issues/8918

**Comment by jryans** [comment]
I agree we should change back. This will also help DevTools align with ESLint rules for m-c generally (which made different choices here).

**Comment by jryans** [comment]
Mozilla config:
```
    "space-before-function-paren": ["error", {
      "anonymous": "never",
      "asyncArrow": "always",
      "named": "never"
    }],
    "generator-star-spacing": ["error", {
      "after": true, 
      "before": false
    }],
```

DevTools config:
```
    "space-before-function-paren": ["error", {
      "anonymous": "always", 
      "named": "never"
    }],
   <generator-star-spacing inherited from Mozilla>
```

Since this was last [discussed](https://bugzilla.mozilla.org/show_bug.cgi?id=1263258), the `generator-star-spacing` rule [learned](https://eslint.org/docs/rules/generator-star-spacing) more options like `method` which we might be interesting here.

**Comment by juliandescottes** [comment]
In favor of aligning with mozilla-central rules. Can we align though? From the last comment I get the feeling we would still need to deviate a bit? for this `method` option? Or is this something we could hope to push to the mozilla-central rules?

**Comment by jryans** [comment]
> Can we align though? From the last comment I get the feeling we would still need to deviate a bit? for this method option? Or is this something we could hope to push to the mozilla-central rules?

I think we'd either have to push for a change to Mozilla rules or decide to conform as they are. (Given that most of our generators are disappearing now with async / await, I personally don't feel strongly about what they look like anymore.)

**Comment by jasonLaster** [comment]
I think we should really try to do `function name() {}` even if it  means that we need to disable the eslint rule for a generator case given that we realistically don't have any generators at the moment.

**Comment by juliandescottes** [comment]
> @ochameau did a great job converting our Tasks to Promises here. It looks like we have two additional minor uses here2.

@jasonLaster  This change only concerned the server. If you look for usage of `function*` in devtools, we still have [thousands of matches](https://searchfox.org/mozilla-central/search?q=function*&path=devtools). Not that it blocks discussing this RFC, but we still still have a lot of `function*`.

> I think we'd either have to push for a change to Mozilla rules or decide to conform as they are. (Given that most of our generators are disappearing now with async / await, I personally don't feel strongly about what they look like anymore.)

As long as we are using the same rules as in m-c for the options that they also define, that's still an improvement. Worst case scenario we have to duplicate the rule and add our option.

Huge eslint --fix patch though :)

**Comment by julienw** [comment]
Use same thing as mozilla's config. One less thing to discuss. More time to code.

**Comment by juliandescottes** [comment]
This RFC was reviewed and accepted. We will switch to enforce no space before the function paren. 

There are still some details to figure out along the way, mainly "what to do about generators", but since we are not really adding new ones anymore, either way is fine.

Follow up action should be to create a Bug to perform the change:
- take a decision on generators
- update eslint configuration
- update code to pass eslint

@jasonLaster do you want to take care of creating the Bug?

**Comment by julienw** [comment]
> take a decision on generators

Shouldn't this be done here too?

**Comment by juliandescottes** [comment]
> Shouldn't this be done here too?

The assumption is that this depends on how the current options for eslint can work for our needs. So it's not just deciding it's "starting to do this and make the most of what's available". If we can enforce something for generators great, if not that's fine.

**Comment by julienw** [comment]
I'm a strong believer that our needs are: use the mozilla common configuration.

**Comment by juliandescottes** [comment]
> I'm a strong believer that our needs are: use the mozilla common configuration.

We will, they just don't define anything regarding generators.

**Comment by juliandescottes** [comment]
Follow-up bug created at https://bugzilla.mozilla.org/show_bug.cgi?id=1443081

**Comment by juliandescottes** [comment]
Landing in https://bugzilla.mozilla.org/show_bug.cgi?id=1443081

**Comment by juliandescottes** [comment]
Bug has landed on central.
