### ISSUE TITLE
Consider removing the Firebug theme

### ISSUE THREAD

**Issue by nt1m** [devtools-html/rfcs#42]
The Firebug theme has been unmaintained for a couple of releases now. A lot of bugs touching the devtools UI regress the Firebug theme (bug 1360459 is an example), and those Firebug theme bugs are relatively low priority...

A quick search for firebug theme bugs shows how inconsistent/broken the theme is: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ALL%20firebug%20theme&list_id=14028048

It also complicates quite a lot the CSS: https://dxr.mozilla.org/mozilla-central/search?q=.theme-firebug+path%3Adevtools&redirect=true

One consequence of this is dead code: https://bugzilla.mozilla.org/show_bug.cgi?id=1408198#c13.

I would be for putting this through "Great or dead", at the moment it is not great, so I would vote for dead. If the Firebug theme is something that's still wanted, I would rather remove it and potentially bring it back via a WebExtension devtools theming API [bug 1414196](https://bugzilla.mozilla.org/show_bug.cgi?id=1414196).

What do you think ?

**Comment by captainbrosset** [comment]
This theme is too costly to maintain. Among other things, it hurt us quite badly during Q4 of 2017 when we implemented the photon-like theme in DevTools.
I don't think this theme is worth the technical cost.

We have some telemetry data about its usage here: https://mzl.la/2yuzs3r
If I understand this data correctly, here's what it looks like:

<img width="569" alt="stats" src="https://user-images.githubusercontent.com/1152698/36658607-9d5e8436-1ad1-11e8-82ed-d6476fe95123.PNG">

So, usage is still around 6%, and just half of the dark theme. So not totally negligible.

We have to remember though that during our Firebug->devtools transition plan, we offered people to switch to DevTools and when they did so, the Firebug theme was the default. So there is some amount of people within this 6% slice that got the theme automatically and never bothered to change it (maybe don't know how, maybe don't care).
Moving them to the light theme might be seen as a welcome modern re-design.

One option forward would be to switch people to the light theme and measure how many of them switch back to Firebug.
This sounds like it would give us  a definitive answer on whether we can get rid of the theme (if it comes with the proper messaging about why they were switched to a different theme and how to revert it), but I don't know how much engineering effort is required to put that in place, and how soon we can have the results.

My opinion is, if it takes one person to write some code for a week, get it tested, liaise with the experiment people, oversee the whole process, etc. then it's not worth it. It adds to the already high cost and prevents us from doing more design changes right now.

If there's a chance we can have this data a lot quicker, then I think we should run the study.

**Comment by janodvarko** [comment]
I agree with the removal.

> My opinion is, if it takes one person to write some code for a week, get it tested, liaise with the
> experiment people, oversee the whole process, etc. then it's not worth it. It adds to the already high
> cost and prevents us from doing more design changes right now.

Yes. I would vote for not investing more time into it. We can profit long term if maintaining just light & dark themes.

Honza

**Comment by gregtatum** [comment]
I think we should just remove it because of the high technical cost, and lack of quality. At this point it seems like it was a migration strategy that has served its purpose.

**Comment by violasong** [comment]
I would love it if we could remove it but show a friendly off-boarding message for Firebug theme users that appears where DevTools would normally be when they open DevTools. It could explain: 

- Acknowledgement of the wonders of Firebug with Link to Honza's nice firebug memorial blog post
- Explanation of the significant cost of continuing upkeep of this theme
- Encouragement to please try our "clean new light theme, designed for great readability, or our subtle dark theme" with a link to my Nightly post on research and reasoning for the new theme colors
- Below there could be big buttons for [Switch to Light Theme] [Switch to Dark Theme], to give them some choice
- Maybe a Discourse feedback link
- Maybe a suggestion that we may allow Firebug themes to come back via custom theming in the future (not sure how much we want to promise this but we could suggest people vote in the bug if this is a big issue for them)

**Comment by Garbee** [comment]
I think that's a little bit too much info for a quick off-boarding message in the interface. I think based on the info shown, it simply is a detriment to the development team to continue maintaining. So remove it and auto-shift users to the default theme. No messages in-view or other things. If there is enough noise after-the-fact, perhaps do a quick blog post explaining the situation for easy search finding.

Most users will probably not even care really. Some will still have their heart on for Firebug's look, but it's age is far past.

The team should not set a precedent of having in-tool alerts to non-critical changes. Things need to evolve over time and users should expect that. A theme change is not affecting the workflow people have, just how it looks visually. In my opinion, if workflow isn't touched users shouldn't need to be coddled and have information thrown at them. They'll adapt as they always have.

**Comment by juliandescottes** [comment]
Looks like everybody is ok to remove the theme but we need to agree on how to do this now.

Remaining questions to clarify:
- should we notify users they are switched (with a popup, console message, etc...). I like the suggestions from @violasong , we just need to keep the cost for this removal reasonable
- do we want to gather data before acting (@captainbrosset not sure what you mean by study/experiment, are you thinking about going through shield studies for this?)
- do we want to keep the Firebug theme around or do we just remove it straight away

Ultimately I guess this is more of a product decision. However anything beyond what @Garbee suggested seems costly enough to be moved and prioritized into the backlog.

**Comment by violasong** [comment]
Just wanted to add that for my solution, it could be technically very simple - perhaps a page on http://firefox-dev.tools/ that opens in a new tab when Firebug theme users open up DevTools for the first time after we remove the theme. It wouldn't take much of my time to write it and mark it up.

**Comment by bgrins** [comment]
I do like the idea of providing a devtools theming API which would allow for partially restoring it (at least for things that are controllable via css variables like the syntax highlighting colors and primary toolbar / tab coloring). But I don't think we need to block on that before proceeding here.

An incremental first step to lowering the maintenance burden and ongoing accidental bustage could be to remove all non-css-variable changes in the theme (i.e. https://github.com/bgrins/devtools-patches/blob/master/firebug-variables) which makes the UI look like:

<img width="1069" alt="screenshot 2018-03-01 09 50 42" src="https://user-images.githubusercontent.com/95570/36860531-5ae20d5a-1d36-11e8-97dd-78f2742f2a88.png">

Instead of:

<img width="1069" alt="screenshot 2018-03-01 09 54 30" src="https://user-images.githubusercontent.com/95570/36860594-91619882-1d36-11e8-884c-fe963e7f14c0.png">

**Comment by Garbee** [comment]
>  perhaps a page on http://firefox-dev.tools/ that opens in a new tab when Firebug theme users open up DevTools for the first time after we remove the theme.

This seems very extreme and personally I find it aggravating when it happens to me. I'd strongly urge not to ever consider auto-opening a tab like that. It's an overbearing method of moving a user from the mental context they are in into another. Users are trying to *get work done*, let's not switch their contexts on them. That is wrong.

A blog post about the changes sounds good to me. Very reasonable. However, let's not make the assumption that users care so much they'd want their context changed upon opening the tools. Let users search for the topic and find the blog post on their own if they care.

@juliandescottes has a good point on using a console log statement for this. Subtle, non-intrusive, developers have the option to see it and click the link for more info. But only if they chose to shift into that context. However, from past experience with Chrome's console warnings, even if developers do see the messages, few read them much less click through links in them. So, could just be a futile attempt in the end.

**Comment by captainbrosset** [comment]
> should we notify users they are switched (with a popup, console message, etc...). I like the suggestions from @violasong , we just need to keep the cost for this removal reasonable

My feeling about this is let's do whatever is to cheapest. As Greg said, the Firebug theme was a migration strategy that has served its purpose. No need for us to invest more in this. We have already invested considerable efforts in trying to migrate the Firebug user base in the past. This was  nicely concluded with Honza's good bye post: https://getfirebug.com/

A console message feels good to me. We have a simple API for sending console warnings in a page's context from DevTools. Probably only requires a few lines of code in the theme-switcher module.

But let's leave the final decision to our product owners @digitarald and @martinbalfanz.

> do we want to gather data before acting (@captainbrosset not sure what you mean by study/experiment, are you thinking about going through shield studies for this?)

I didn't have any specific solution in mind for this. The idea was to run an experiment that would just switch all firebug theme users to the light theme, and measure how many switched back. So whatever allowed us to do this.

But knowing how these experiments require planning, code, documentation and testing, I just don't think it's worth it.

> Ultimately I guess this is more of a product decision.

Agreed. The right people have been pinged here. Let's wait for product guidance on this and act accordingly.

**Comment by digitarald** [comment]
The lack of quality and required investment is the main reason for me to vote *to remove it* and switch users over to the light theme, giving users a better experience of what they are stuck with now. Secondly since Firebug theme was meant to ease the transition from Firebug to devtools; and users are no longer "migrating" the foremost reason to have it is also resolved.

**Comment by juliandescottes** [comment]
This has been accepted and will be moved to a backlog item for DevTools. The actual implementation of the removal will be decided when the backlog item will be refined.

**Comment by juliandescottes** [comment]
A backlog item has been logged, closing.

**Comment by juliandescottes** [comment]
Done per https://bugzilla.mozilla.org/show_bug.cgi?id=1378108
