### ISSUE TITLE
DevTools telemetry.js should mirror APIs from Services.telemetry

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/rfcs#47]
DevTools uses a wrapper around Services.telemetry: [telemetry.js](https://searchfox.org/mozilla-central/rev/11a2ae294f50049e12515b5821f5a396d951aacb/devtools/client/shared/telemetry.js). This helper makes data-review complicated because our code looks very different from regular telemetry code. We often ask for help from data-peers to advise us on Telemetry so we should make our code easy to understand for peers outside of DevTools team.

The goal of this RFC is to propose a renaming of our APIs to mirror Services.telemetry, while still keeping our helper alive.

(Note: I am leaving the recently added Event telemetry APIs out of this RFC for now.)

### Usage

While the helper is heavily used in DevTools, it is not used consistently everywhere. A quick search reveals that we still call Services.telemetry in several spots, making our own code inconsistent: https://searchfox.org/mozilla-central/search?q=Services.telemetry&case=false&regexp=false&path=devtools%2F

### Pros

- try/catch around all APIs make it easier to integrate new probes without doing full builds
- lists most DevTools probes (incomplete because we don't use it for all our telemetry code)
- toolOpened/toolClosed are nice abstractions for our architecture
- easy to mock for Debugger/Launchpad apps?

### Cons

- method names are very different from Telemetry ones
- inconsistent with the rest of mozilla-central (even within DevTools, we have code not using the helper)
- not using the [telemetry provided timers](https://searchfox.org/mozilla-central/rev/11a2ae294f50049e12515b5821f5a396d951aacb/toolkit/components/telemetry/TelemetryStopwatch.jsm)

## APIs in telemetry.js 

`T` represents `Services.telemetry` here:
- log: calls `T.getHistogramById().add()`
- logKeyed: calls `T.getKeyedHistogramById().add()`
- logScalar: calls `T.scalarSet()`
- logCountScalar: calls `T.scalarAdd()`
- logKeyedScalar: calls `T.keyedScalarAdd()`
- startTimer: doesn't call anything from telemetry but starts a timer
- stopTimer: if a corresponding timer is found, calls either `T.getHistogramById().add()` or `T.getKeyedHistogramById().add()`
- toolOpened: may call: `T.getHistogramById().add()`, `T.scalarSet()`, `T.keyedScalarAdd()` and `startTimer()` 
- actionOccurred: alias to `toolOpened()`
- toolClosed: may call `stopTimer()`
- logOncePerBrowserVersion: complex method to check if a probe was already logged, ends up calling `T.getHistogramById().add()`

## Proposal

_The proposal is all of the following items_

1. Rename all log* methods

All the low level methods are renamed to match the real method names from Services.telemetry. Example: `log` is replaced by `getHistogramById`. The caller is responsible for calling `add()` afterwards. In case the histogram doesn't exist, we can return a mock `{ add: () => {} }`.

2. Rename startTimer/stopTimer

Replace startTimer/stopTimer by start/finish and startKeyed/finishKeyed. At the same time switch the implementation to call the real TelemetryStopwatch methods.

3. Remove actionOccurred

This is just an alias, remove it. All the current call sites can directly use log* APIs here.

4. Cleanup toolOpened/toolClosed

There is no equivalent to toolOpened/toolClosed. However we abuse this method at the moment, calling it in situations which have nothing to do with a tool "opening": toolOpened("toolbox"), toolOpened("gridInspectorShowGridAreasOverlayChecked"), toolOpened("copyuniquecssselector") etc...
Anything that doesn't have a timer should not use toolOpened(). After this cleanup is performed, maybe we could reassess toolOpened and see if it fits better in toolbox.js than in telemetry.js?

5. Consistent usage of telemetry.js

All the code in DevTools should interact with Telemetry in the same way. DevTools call sites that rely on Services.telemetry should be migrated to the helper.

**Comment by gabrielluong** [comment]
Full support of this.

**Comment by juliandescottes** [comment]
This RFC was reviewed and accepted! @MikeRatcliffe did you already start logging bugs to implement this? If yes could you link them here?

**Comment by juliandescottes** [comment]
Looks like this is already tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1458202 , thanks @MikeRatcliffe .

Closing.
