### ISSUE TITLE
Move all panels to devtools/client/panels subfolder

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/rfcs#49]
(originally proposed by @sole in the review for https://bugzilla.mozilla.org/show_bug.cgi?id=1445197)

Currently, `devtools/client` contains various folders with different roles, including panels.

The proposal for this RFC is to move all panel folders to a `panels` subfolder to clearly differentiate them from more general purpose folders such as "framework" or "preferences". This will also make it easy for us to have an overview of how many different panels we maintain. A potential exception is scratchpad, which is both a panel and a standalone tool.

**Comment by ochameau** [comment]
> The proposal for this RFC is to move all panel folders to a panels subfolder to clearly differentiate them from more general purpose folders such as "framework" or "preferences".

While I agree that it could be valuable to sort `client` folder, this proposal adds another folder to access the most commonly edited files.

I may see more value in sorting out what aren't tools, nor panels from `devtools/client/`:

- `framework` purpose became less clear over time. It is part of firefox integration/toolbox/browser toolbox, but it also includes "targets" and the connect screen which looks pretty random set of things.

- `preferences` may be reorganized into a clearer "firefox integration" folder.

- `themes` looks like a relic from old theming system. May be we could move css into each tool now? Otherwise `themes` and `locales` may be good candidates for `devtools/shared/`?

- `definition.js` and `menus.js` may be moved into a "firefox integration" folder as well.

> This will also make it easy for us to have an overview of how many different panels we maintain.

I'm not sure this is a solid argument. You may just look at options panel. Also if we are so lost in how many panels we have, this highlights some other issue that won't be addressed with a code move/cleanup.

**Comment by juliandescottes** [comment]
Thanks for the feedback! Some comments and questions below.

> this proposal adds another folder to access the most commonly edited files.

Genuinely curious: why is this an issue?

> I may see more value in sorting out what aren't tools, nor panels from devtools/client/

This assumes it is good to group tools (eg webide, aboutdebugging etc...) and panels. While not a critical issue, if we have a folder dedicated to panels, with all panels using a similar architecture, then having those exotic tools next to it will make it harder to understand how our framework works.

Where do you propose to move those other folders? Is the firefox-integration folder supposed to be under devtools/ or under devtools/client/ ?

Here is the list of folder we currently have in client/ which are not panels nor tools: 'framework', 'locales', 'preferences', 'shared', 'sourceeditor', 'themes'. And here are the tools: 'aboutdebugging', 'commandline', 'jsonview', 'responsive.html', 'webide'.

> I'm not sure this is a solid argument. You may just look at options panel. 

Looking at the options panel requires prior knowledge that you will find this information in the options panel?

> Also if we are so lost in how many panels we have, this highlights some other issue that won't be addressed with a code move/cleanup.

A practical example: I spotted yesterday the client/animationinspector folder, while I had just seen client/inspector/animation. I was confused, not sure if animationinspector was a new dedicated panel for animations, while inspector/animation was the old version in the inspector. Turns out animationinspector was the old one and inspector/animation is a new one (but both are just inspector sub-panels). A clear folder hierarchy with explicit rules would have prevented this kind of confusion from appearing.

**Comment by gregtatum** [comment]
> this proposal adds another folder to access the most commonly edited files.

I agree that separating out panels into something distinct would be helpful, but I strongly agree with the above quoted sentiment. I find it difficult to navigate deeply into a hierarchy of folders. It makes the panels hard to discover, and I am often typing full paths when working on the files. This includes navigating in my editor, working with version control, and when running tests. It is nice to have common files with short paths.

We could split `client` into two folders, I'm not sure on the names but, something like `panels` and `client` might be serviceable. Or maybe `integration` as @ochameau suggested. I'm not particularly opinionated on the naming.

`devtools/panels/memory`
`devtools/panels/performance`
...
`devtools/client/locales`
`devtools/client/framework`
...

**Comment by juliandescottes** [comment]
>  I find it difficult to navigate deeply into a hierarchy of folders. It makes the panels hard to discover, and I am often typing full paths when working on the files. This includes navigating in my editor, working with version control, and when running tests. It is nice to have common files with short paths.

> As Greg said, more characters to write in terminal, more click in Tree's UI, longer string to copies from treeherder/mochitest, ... Like very small but common overhead.

OK, thanks for sharing. The mental burden of having vastly different folders under `client` feels like a bigger issue to me, but that's obviously subjective.

> We could split client into two folders, I'm not sure on the names but, something like panels and client might be serviceable. 

`devtools/panels` felt like an acceptable compromise to me, even though I share @ochameau 's worries about having this outside of client.  

> Themes for example are better kept next to panels. So even if we introduce a dedicated panels folder, we may want to keep this folder next to them. sourceeditor looks like something for devtools/client/shared. The right location for locales is harder to define. While all the other folder are for non-panel tools.

Not sure about re-purposing this RFC to a cleanup of `client`. I think it is harder to move all the vaguely defined folders to other locations. client/framework contains all the glue to load panels, it is a really important folder, should we hide it in a "firefox-integration" folder? We have shared/preferences, startup/preferences, so having client/firefox-integration/preferences feels weird.

That might be a good candidate for separate bugs or separate RFCs. I would propose to keep this RFC about grouping panel folders together. 

> Oh that's an interesting example as it is a very old folder (bug 1105825)! Hopefully, the new one is in the right location. But at the same time, no one had any issue with that for 3 years ;)

I had seen the folder before :) this was not an issue until another similar folder appeared, which made me wonder about their respective roles. The new folder in inspector/animation was created at the end of 2017. That's what prompted the confusion for me, and that's where a clearer folder hierarchy would have been helpful. (note: we now moved the "old one" to client/inspector/animation-old)

**Comment by nt1m** [comment]
'responsive.html' or 'jsonview' are not vastly different from panels, in terms of architecture (they use devtools themes/CSS, they're web apps, ...). Separating them from 'panels' might give the impression that they're radically different in terms of architecture.

**Comment by juliandescottes** [comment]
This RFC was reviewed today and we decided to close and reject it. While we agree the client folder could use a cleanup, the proposal here didn't reach a consensus. Main reasons are:
- having an additional folder will make day to day actions more painful
- no consensus on separating tools and panels

While this RFC is rejected, feel free to file bugs or new RFCs to cleanup the `client` folder. Some of the suggestions from https://github.com/devtools-html/rfcs/issues/49#issuecomment-383833783 can probably be expanded and already improve the understanding of our client folder.
