### ISSUE TITLE
Charter for Debug Info API Standard

### ISSUE THREAD

**Issue by codehag** [devtools-html/rfcs#52]
As I mentioned in our previous devtools meetings, we are planning on creating a new standards working group under the W3C to work along side the WASM Debugging working group. The goal of this new one will be to combine the requirements of our two primary targets, JavaScript and WASM, and help coordinate the design of the api. The api itself will provide a way for debuggers and other tools to get information about a compiled piece of code, and will be source agnostic. This means that the debugging info could be DWARF, a .net server, sourcemaps, sourcemaps.next as proposed by fitzgen, or any other format.

I would like to get feedback on the charter, adapted from the WASM debug charter:

# Debug Info API Working Group Charter
## Goals
The mission of this group is to provide a forum for pre-standardization collaboration on debugging capabilities for web compile targets such as WebAssembly and JavaScript.
## Scope
The Group will aggregate and compile the requirements of other working groups and ensure that communication between the JavaScript and WebAssembly working groups is smooth, and provide a forum for discussion between compile source language authors and targets. Topics include:
- Request and Response format to the API
- Extensibility of the API
- Interaction with browsers or other embedders (e.g. developer tools, debugging, profiling)
- Interaction with external debuggers and IDEs (VS Code)
### Specifications
The group may produce several kinds of specification-related work output:
- Extensions or amendments to existing specifications (e.g. Wasm core or web spec, DWARF, EcmaScript)
- Creation of new specifications in standards bodies or working groups (e.g. Wasm WG, TC39, or future general web-debugging standards working group)
### Non-normative reports
The Group may produce non-normative material such as requirements documents, recommendations, and use cases.
### Software
The Group may produce software related to Web based debugging. Capabilities may include:
- Debug info encoding or translation
- Program instrumentation or analysis
- Interactive debuggers or profilers
- Test suites

**Comment by sole** [comment]
Let's step back a bit:
1) what are these charters?
2) how do they relate to DevTools? 
3) Who interacts with the charter? All the team? Only some people? who?  Should they be giving feedback about this?
4) What are the implications of this charter with regards to DevTools day to day? What are the consequences of not getting involved on it?
5) Who is actively working on this so far? How is it in other browsers?

Also in light of the new RFC approach -which we're still working on, but bear with me- do you think this is the right place to get feedback about the charter? It is not clear to me what kind of feedback you're seeking, and it isn't clear either how the charter might affect DevTools.

Hope this helps unblock this very dormant issue.

**Comment by sole** [comment]
Thanks!

So I'm trying to put myself in the position of, for example, a Console owner, and I don't know what to answer, because I don't really know what the question is.

Is the question "what do you think of this proposal to create a charter?" If that's the case, I could imagine one answer is "sounds good to have standards in this field", but I think the goals are so vague I can't find any objection (other than "so who's going to do this coordination work?").

I think once you clarify this we can ping potentially interested parties to see what do they think :-)

**Comment by codehag** [comment]
i will close this for now so we stop looking at it!
